### ISSUE TITLE
Map view crash the apps cordova 5.1.1

### ISSUE THREAD

**Issue by Jerome2606** [Nipher/phonegap-googlemaps-plugin#2]
Hi,

Thanks for your job, now when I run on Android the build works.
But, my app crash when I enter on the view where the map is.

Versions:

```
cordova 5.1.1
ionic 1.6.3
cordova-android 4.0.2
```

logcat trace:

```
E/AndroidRuntime(17092): java.lang.RuntimeException: An error occured while executing doInBackground()

E/AndroidRuntime(17092):    at android.os.AsyncTask$3.done(AsyncTask.java:300)

E/AndroidRuntime(17092):    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)

E/AndroidRuntime(17092):    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)

E/AndroidRuntime(17092):    at java.util.concurrent.FutureTask.run(FutureTask.java:242)

E/AndroidRuntime(17092):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)

E/AndroidRuntime(17092):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

E/AndroidRuntime(17092):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

E/AndroidRuntime(17092):    at java.lang.Thread.run(Thread.java:818)

E/AndroidRuntime(17092): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'android.app.Activity org.apache.cordova.CordovaInterface.getActivity()' on a null object reference

E/AndroidRuntime(17092):    at plugin.google.maps.PluginMarker$7.doInBackground(PluginMarker.java:716)

E/AndroidRuntime(17092):    at plugin.google.maps.PluginMarker$7.doInBackground(PluginMarker.java:683)

E/AndroidRuntime(17092):    at android.os.AsyncTask$2.call(AsyncTask.java:288)

E/AndroidRuntime(17092):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)

E/AndroidRuntime(17092):    ... 4 more
```

**Comment by Jerome2606** [comment]
After some reading, you need to use this forks:
https://github.com/dubcanada/phonegap-googlemaps-plugin
